// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /Users/Martina/Desktop/CMS/GIT_HUB/displaced_11/./Analysis_1file.h;
#pragma link C++ defined_in "/Users/Martina/Desktop/CMS/GIT_HUB/displaced_11/./Analysis_1file.cc";

#endif
